import ads from './Ads-min.png'
import bakedChickenWingsAsianStyleTomatoesSaucePlate from './baked-chicken-wings-asian-style-tomatoes-sauce-plate-min.png'
import barbequeSpicySandwichesWithChips from './Barbeque Spicy Sandwiches with Chips -min.png'
import bigAndJuicyWagyuBeefCheeseburger from './Big and Juicy Wagyu Beef Cheeseburger-min.png'
import breakfast from './breakfast-min.png'
import cauliflowerWalnutVegetarianTacoMeat from './Cauliflower Walnut Vegetarian Taco Meat-min.png'
import chickenMeatballsWithCreamCheese from './Chicken Meatballs with Cream Cheese-min.png'
import chickenRamenSoupWithMushroom from './Chicken Ramen Soup with Mushroom -min.png'
import chocolate from './chocolate-min.png'
import dessert from './dessert-min.png'
import everyoneCanBeAChefInTheirOwnKitchen from './everyone-can-be-a-chef-in-their-own-kitchen-min.png'
import facebook from './facebook.svg'
import firecrackerVeganLettuceWrapsSpicy from './Firecracker Vegan Lettuce Wraps - Spicy! -min.png'
import forkKnife from './ForkKnife.svg'
import freshAndHealthyMixedMayonnaiseSalad from './Fresh and Healthy Mixed Mayonnaise Salad-min.png'
import freshLimeRoastedSalmonWithGingerSauce from './Fresh Lime Roasted Salmon with Ginger Sauce-min.png'
import fruityPancakeWithOrangeBlueberry from './Fruity Pancake with Orange & Blueberry-min.png'
import handpickedRecipes from './handpicked-recipes-min.png'
import healthyJapaneseFriedRiceWithAsparagus from './Healthy Japanese Fried Rice with Asparagus-min.png'
import hearth from './Hearth.svg'
import heroPerson from './hero-person-min.png'
import instagram from './instagram.svg'
import logo from './logo.svg'
import lunch from './lunch-min.png'
import meat from './meat-min.png'
import mixedTropicalFruitSaladWithSuperfoodBoosts from './Mixed Tropical Fruit Salad with Superfood Boosts-min.png'
import paper from './paper.png'
import play from './PlayCircle.svg'
import post1 from './post-1-min.png'
import post2 from './post-2-min.png'
import post3 from './post-3-min.png'
import post4 from './post-4-min.png'
import rainbowChickenSaladWithAlmondHoneyMustardDressing from './Rainbow Chicken Salad with Almond Honey Mustard Dressing-min.png'
import strawberryOatmealPancakeWithHoneySyrup from './Strawberry Oatmeal Pancake with Honey Syrup-min.png'
import subscribe1 from './subscribe-1-min.png'
import subscribe2 from './subscribe-2-min.png'
import theBestEasyOnePotChickenAndRice from './The Best Easy One Pot Chicken and Rice-min.png'
import theCreamiestCreamyChickenAndBaconPasta from './The Creamiest Creamy Chicken and Bacon Pasta-min.png'
import timer from './Timer.svg'
import twitter from './twitter.svg'
import vegan from './vegan-min.png'
