import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.scss'
import {
  handpickedRecipes,
  heroPerson,
  bakedChickenWingsAsianStyleTomatoesSaucePlate,
  paper,
  timer,
  forkKnife,
  play,
  breakfast,
  vegan,
  meat,
  dessert,
  lunch,
  chocolate,
  ads,
} from '../assets'
import Category from '../components/Category'
import getServer from '../utils/getServer'
import { Recipe } from '../mongodb'
import RecipeCard from '../components/RecipeCard'

type Props = {
  recipesData: Recipe[]
}

const Home: React.FC<Props> = ({ recipesData }) => {
  let recipes = recipesData
  return (
    <>
      <Head>
        <title>Foodieland. Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section id={style.hero}>
        <div className={style['info-container']}>
          <div className={style['hot-recipes']}>
            <Image src={paper} alt='paper' />
            <p>Hot Recipes</p>
          </div>
          <div className={style['main-info']}>
            <h1>Spicy delicious chicken wings</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
              aliqut enim ad minim{' '}
            </p>
            <div className={style['additional-info']}>
              <div>
                <Image src={timer} alt='timer' />
                <p>30 Minutes</p>
              </div>
              <div>
                <Image src={forkKnife} alt='fork knife' />
                <p>Chicken</p>
              </div>
            </div>
          </div>
          <div className={style.publisher}>
            <div className={style.person}>
              <Image src={heroPerson} alt='person' />
              <div>
                <p>John Smith</p>
                <p>15 March 2022</p>
              </div>
            </div>
            <div className={style['publisher-recipes']}>
              <p>View Recipes</p>
              <Image src={play} alt='play' />
            </div>
          </div>
          <Image className={style.badge} src={handpickedRecipes} alt='handchecked recipes' />
        </div>
        <div className={style['image-container']}>
          <Image src={bakedChickenWingsAsianStyleTomatoesSaucePlate} alt='baked chicken wings asian style tomatoes sauce plate' />
        </div>
      </section>

      <section id={style.categories}>
        <div className={style['title-container']}>
          <h2>Categories</h2>
          <a href='#'>View All Categories</a>
        </div>
        <div className={style['categories-container']}>
          <Category name='breakfast' image={breakfast} />
          <Category name='vegan' image={vegan} />
          <Category name='meat' image={meat} />
          <Category name='dessert' image={dessert} />
          <Category name='lunch' image={lunch} />
          <Category name='chocolate' image={chocolate} />
        </div>
      </section>

      <section id={style['recipes-1']}>
        <div className={style['title-container']}>
          <h2>Simple and tasty recipes</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetuipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqut
            enim ad minim
          </p>
        </div>
        <div className={style['recipes-container']}>
          {recipes.map((i: Recipe, index) => {
            if (index < 8) {
              return <RecipeCard key={i._id} data={i} type={1} index={index} />
            }
          })}
          <Image className={style.ad} src={ads} alt='ad' />
        </div>
      </section>
    </>
  )
}

export async function getStaticProps() {
  const server = getServer()
  const recipes: Recipe[] = await fetch(`${server}/api/recipes`)
    .then((res) => res.json())
    .then((res) => {
      return res
    })
  return {
    props: { recipesData: recipes },
  }
}

export default Home
