import Head from 'next/head'

const recipes = () => {
  return (
    <>
      <Head>
        <title>Foodieland. Recipes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export default recipes
